name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Build and Test
    - name: Build and Test
      run: |
        xcodebuild clean test \
          -project CatBrowser.xcodeproj \
          -scheme CatBrowser \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          CODE_SIGNING_ALLOWED=NO

